[package]
name = "marketplace"
version = "1.0.0"
authors = []

[addresses]
marketplace = "_"

[dev-addresses]
marketplace = "0xcafe"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
